enum RolesEnum {
  DISPATCH_OFFICER = "DISPATCH_OFFICER",
  BRANCH_MANAGER = "BRANCH_MANAGER",
  ADMIN = "ADMIN",
  CUSTOMER = "CUSTOMER",
  DELIVERY_OFFICER = "DELIVERY_OFFICER",
}

export default RolesEnum;
